### ISSUE TITLE
Should push out 0.3 to rubygems

### ISSUE THREAD

**Issue by capotej** [fetep/ruby-statsdserver#1]
Otherwise, great project :)

**Comment by fetep** [comment]
there is already another "statsd" gem published, so I published this as "petef-statsd" (0.3).  thanks!

**Comment by capotej** [comment]
ah, that explains it. this is working great in production btw

**Comment by fetep** [comment]
awesome!  I'm also running it in prod.  are you using the tcp or amqp output?  (amqp, here.)

**Comment by capotej** [comment]
tcp output, does graphite do amqp? or you just have it behind something like rabbitmq

**Comment by fetep** [comment]
yes, graphite does AMQP (you'll want to turn on the AMQP_METRICS_IN_BODY option, too).  I use rabbitmq for my broker.

the main reason i ship stats to amqp is so i can also analyze and alert on them; some work on that is here: https://github.com/fetep/cepmon  (feeds metric stream to Esper, which is a sweet CEP engine).  working on making a holt-winters time series prediction algorithm thingy work well, to do thresholdless alerting.
